#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_PATCH 0
#define VERSION_BUILD 0

#define FIX_VERSION_MAJOR 1
#define FIX_VERSION_MINOR 2
#define FIX_VERSION_PATCH 0
#define FIX_VERSION_BUILD 0

#define DIGITSHIELD_VERSION_MAJOR 1
#define DIGITSHIELD_VERSION_MINOR 2
#define DIGITSHIELD_VERSION_PATCH 0
#define DIGITSHIELD_VERSION_BUILD 0

#define DIGITSHIELD_VERSION "1.2.0"
