#define VERSION_MAJOR 2
#define VERSION_MINOR 99
#define VERSION_PATCH 99
#define VERSION_BUILD 99

#define FIX_VERSION_MAJOR 2
#define FIX_VERSION_MINOR 99
#define FIX_VERSION_PATCH 99
#define FIX_VERSION_BUILD 99

#define DIGITSHIELD_VERSION_MAJOR 1
#define DIGITSHIELD_VERSION_MINOR 0
#define DIGITSHIELD_VERSION_PATCH 0
#define DIGITSHIELD_VERSION_BUILD 0

#define DIGITSHIELD_VERSION "1.0.0"
